#!/usr/bin/env python3
"""Generate typed TS data modules from the vendored spreadsheet CSVs.

Run from repo root:  python scripts/generate_data.py
Outputs to src/data/generated/*.ts
"""
import csv, re, os, json

RAW = os.path.join(os.path.dirname(__file__), "raw")
ROOT = os.path.join(os.path.dirname(__file__), "..")
OUT = os.path.join(ROOT, "apps", "web", "src", "data", "generated")
# JSON mirror for the API seed (DB is source of truth in prod; this seeds it).
JSON_OUT = os.path.join(ROOT, "packages", "shared", "catalog")
os.makedirs(OUT, exist_ok=True)
os.makedirs(JSON_OUT, exist_ok=True)

def slug(*parts):
    s = "-".join(p for p in parts if p)
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "x"

def js(v):
    return json.dumps(v, ensure_ascii=False)

def header(note):
    return f"// AUTO-GENERATED by scripts/generate_data.py — do not edit by hand.\n// {note}\n\n"

# ---------------- WATER ----------------
def gen_water():
    waters = []
    seen = set()
    with open(os.path.join(RAW, "water.csv"), encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.lower().startswith("brand air"):
                continue
            m = re.match(r"^(.*?)\s+([\d.]+(?:\s*-\s*[\d.]+)?)\s*pH\s*[–-]\s*(\d+)\s*ppm", line)
            if not m:
                continue
            name = m.group(1).strip()
            ph_raw = m.group(2).replace(" ", "")
            if "-" in ph_raw:
                a, b = ph_raw.split("-")
                ph = round((float(a) + float(b)) / 2, 1)
                ph_label = ph_raw.replace("-", "–")
            else:
                ph = float(ph_raw)
                ph_label = ph_raw
            ppm = int(m.group(3))
            wid = slug(name)
            if wid in seen:
                continue
            seen.add(wid)
            waters.append({"id": wid, "name": name, "ph": ph, "phLabel": ph_label, "ppm": ppm})
    body = header("Bottled water brands: pH + TDS (ppm). Source: domain spreadsheet.")
    body += "export interface Water { id: string; name: string; ph: number; phLabel: string; ppm: number }\n\n"
    body += "export const WATERS: Water[] = [\n"
    for w in waters:
        body += f"  {{ id: {js(w['id'])}, name: {js(w['name'])}, ph: {w['ph']}, phLabel: {js(w['phLabel'])}, ppm: {w['ppm']} }},\n"
    body += "]\n"
    write("waters.ts", body)
    write_json("waters.json", waters)
    return len(waters)

# ---------------- BEANS (variety-first: variety > country > region) ----------------
def gen_beans():
    # Sheet cols: Varietas/Klon, Negara, Daerah/Origin, Spesies, Kategori,
    # Cup Potential, Body, Acidity, Sweetness, Tasting Notes. Sorted by variety.
    beans = []
    seen = set()
    with open(os.path.join(RAW, "beans.csv"), encoding="utf-8") as f:
        r = csv.reader(f)
        next(r)
        idx = 0
        for row in r:
            if not row or not row[0].strip():
                continue
            (variety, origin, region, species, category, cup, body, acidity,
             sweetness, notes) = (row + [""] * 10)[:10]
            bid = slug(variety, origin, region)
            if bid in seen:
                bid = slug(variety, origin, region, str(idx))
            seen.add(bid)
            beans.append({
                "id": bid, "variety": variety.strip(), "origin": origin.strip(),
                "region": region.strip(), "species": species.strip(),
                "category": category.strip(), "cupPotential": cup.strip(),
                "body": body.strip(), "acidity": acidity.strip(),
                "sweetness": sweetness.strip(), "notes": notes.strip(),
            })
            idx += 1
    out = header("Coffee beans: variety > country > region + cup profile. Source: domain spreadsheet.")
    out += ("export interface Bean { id: string; variety: string; origin: string; region: string;\n"
            "  species: string; category: string; cupPotential: string; body: string; acidity: string;\n"
            "  sweetness: string; notes: string }\n\n")
    out += "export const BEANS: Bean[] = [\n"
    for b in beans:
        out += "  " + js(b) + ",\n"
    out += "]\n"
    write("beans.ts", out)
    write_json("beans.json", beans)
    return len(beans)

# ---------------- PROCESSES (standalone post-harvest catalog) ----------------
def gen_processes():
    # Sheet cols: Proses pasca panen, Deskripsi Singkat / Cara Kerja, Dampak pada Profil Rasa.
    items = []
    seen = set()
    with open(os.path.join(RAW, "processes.csv"), encoding="utf-8") as f:
        r = csv.reader(f)
        next(r)
        for row in r:
            if not row or not row[0].strip():
                continue
            name, desc, flavor = (row + [""] * 3)[:3]
            pid = slug(name)
            if pid in seen:
                continue
            seen.add(pid)
            items.append({"id": pid, "name": name.strip(), "description": desc.strip(), "flavor": flavor.strip()})
    out = header("Post-harvest processes (standalone). Source: domain spreadsheet.")
    out += "export interface Process { id: string; name: string; description: string; flavor: string }\n\n"
    out += "export const PROCESSES: Process[] = [\n"
    for p in items:
        out += "  " + js(p) + ",\n"
    out += "]\n"
    write("processes.ts", out)
    write_json("processes.json", items)
    return len(items)

# ---------------- DRIPPERS ----------------
def dripper_geo_flow(type_raw):
    t = type_raw.lower()
    immersion = ("immersion" in t) or ("switch" in t)
    if "trapezoid" in t:
        geo = "trapezoid"
    elif "flat" in t:
        geo = "flat"
    elif "conical" in t or "cone" in t:
        geo = "conical"
    elif "hybrid" in t:
        geo = "hybrid"
    else:
        geo = "other"
    # flow factor heuristic
    if "fast" in t:
        flow = 1.28
    elif "no-bypass" in t or "zero-bypass" in t or "no bypass" in t:
        flow = 0.8
    elif immersion or "pressure" in t:
        flow = 0.85
    elif "all-in-one" in t or "chemex" in t:
        flow = 0.7
    elif geo == "conical":
        flow = 1.12
    elif geo == "hybrid":
        flow = 1.0
    elif geo == "flat":
        flow = 0.92
    elif geo == "trapezoid":
        flow = 0.85
    else:
        flow = 1.0
    return geo, round(flow, 2), immersion

def gen_drippers():
    items = []
    seen = set()
    with open(os.path.join(RAW, "dripper.csv"), encoding="utf-8") as f:
        r = csv.reader(f)
        next(r)
        for row in r:
            if not row or not row[0].strip():
                continue
            brand, model, type_raw = (row + ["", "", ""])[:3]
            geo, flow, imm = dripper_geo_flow(type_raw)
            did = slug(brand, model)
            if did in seen:
                did = slug(brand, model, str(len(items)))
            seen.add(did)
            items.append({"id": did, "brand": brand.strip(), "model": model.strip(),
                          "typeRaw": type_raw.strip(), "geometry": geo,
                          "flowFactor": flow, "immersion": imm})
    out = header("Drippers: brand+model, geometry, flow factor, immersion flag. Source: domain spreadsheet.")
    out += ("export interface Dripper { id: string; brand: string; model: string; typeRaw: string;\n"
            "  geometry: 'conical'|'flat'|'trapezoid'|'hybrid'|'other'; flowFactor: number; immersion: boolean }\n\n")
    out += "export const DRIPPERS: Dripper[] = [\n"
    for d in items:
        out += "  " + js(d) + ",\n"
    out += "]\n"
    write("drippers.ts", out)
    write_json("drippers.json", items)
    return len(items)

# ---------------- FILTERS ----------------
FLOW_MAP = {
    "sangat cepat": 1.3, "cepat": 1.15, "sedang-cepat": 1.05, "sedang–cepat": 1.05,
    "sedang": 1.0, "agak lambat": 0.88, "lambat": 0.75, "-": 1.0, "": 1.0,
}
def gen_filters():
    items = []
    seen = set()
    with open(os.path.join(RAW, "filter.csv"), encoding="utf-8") as f:
        r = csv.reader(f)
        next(r)
        for row in r:
            if not row or not row[0].strip():
                continue
            (brand, model, material, flow, body, clarity, sweetness, acidity) = (row + [""] * 8)[:8]
            ff = FLOW_MAP.get(flow.strip().lower(), 1.0)
            fid = slug(brand, model)
            if fid in seen:
                fid = slug(brand, model, str(len(items)))
            seen.add(fid)
            items.append({"id": fid, "brand": brand.strip(), "model": model.strip(),
                          "material": material.strip(), "flowRate": flow.strip(),
                          "flowFactor": ff, "body": body.strip(), "clarity": clarity.strip(),
                          "sweetness": sweetness.strip(), "acidity": acidity.strip()})
    out = header("Paper filters: brand+model, material, flow, cup traits. Source: domain spreadsheet.")
    out += ("export interface PaperFilter { id: string; brand: string; model: string; material: string;\n"
            "  flowRate: string; flowFactor: number; body: string; clarity: string; sweetness: string; acidity: string }\n\n")
    out += "export const FILTERS: PaperFilter[] = [\n"
    for x in items:
        out += "  " + js(x) + ",\n"
    out += "]\n"
    write("filters.ts", out)
    write_json("filters.json", items)
    return len(items)

# ---------------- GRINDERS ----------------
def parse_um(s):
    s = (s or "").strip().lstrip("~").replace("µm", "").strip()
    m = re.search(r"[\d.]+", s)
    return float(m.group(0)) if m else None

def first_sentences(text, n=2):
    text = text.strip()
    parts = re.split(r"(?<=[.])\s+", text)
    return " ".join(parts[:n]).strip()

def gen_grinders():
    # Sheet columns (12): 0 hyperlink, 1 Link, 2 Brand, 3 Model, 4 Min, 5 Max,
    # 6 Grind Range, 7 Total Steps/Clicks, 8 Step Type, 9 Approx µm/step,
    # 10 Characteristics, 11 Verification.
    items = []
    seen = set()
    with open(os.path.join(RAW, "grinder.csv"), encoding="utf-8") as f:
        r = csv.reader(f)
        next(r)
        for row in r:
            if len(row) < 11 or not row[2].strip():
                continue
            brand, model = row[2].strip(), row[3].strip()
            mn = parse_um(row[4]); mx = parse_um(row[5])
            total_steps = row[7].strip()
            step_type = row[8].strip()
            um = parse_um(row[9])
            stepless = "stepless" in step_type.lower() and um is None
            note = first_sentences(row[10], 2) if len(row) > 10 else ""

            # Sheet is fully completed by the owner — ship all grinders active.
            # (Admin can deactivate individually; auto-rule kept here for reference.)
            range_ok = mn is not None and mx is not None and mx > mn
            step_ok = stepless or um is not None
            _auto_active = bool(brand and model and range_ok and step_ok)  # noqa: F841
            active = True

            gid = slug(brand, model)
            if gid in seen:
                gid = slug(brand, model, str(len(items)))
            seen.add(gid)
            items.append({
                "id": gid, "brand": brand, "model": model,
                "minMicron": int(mn) if mn is not None else 0,
                "maxMicron": int(mx) if mx is not None else 0,
                "umPerStep": um, "stepType": step_type, "totalSteps": total_steps,
                "stepless": stepless, "note": note, "active": active,
            })
    out = header("Grinders: brand+model, micron range, step size/type. Source: honestcoffeeguide via domain spreadsheet.")
    out += ("export interface Grinder { id: string; brand: string; model: string; minMicron: number;\n"
            "  maxMicron: number; umPerStep: number | null; stepType: string; totalSteps: string;\n"
            "  stepless: boolean; note: string; active: boolean }\n\n")
    out += "export const GRINDERS: Grinder[] = [\n"
    for g in items:
        out += "  " + js(g) + ",\n"
    out += "]\n\n"
    out += ("/** Suggested setting (clicks/steps from closed) for a target micron, or null if stepless/unknown. */\n"
            "export function suggestSetting(g: Grinder, micron: number): number | null {\n"
            "  if (!g.umPerStep) return null\n"
            "  const clamped = Math.min(g.maxMicron, Math.max(g.minMicron, micron))\n"
            "  return Math.max(0, Math.round((clamped - g.minMicron) / g.umPerStep))\n"
            "}\n")
    write("grinders.ts", out)
    write_json("grinders.json", items)
    return len(items)

def write(name, body):
    with open(os.path.join(OUT, name), "w", encoding="utf-8", newline="\n") as f:
        f.write(body)

def write_json(name, data):
    with open(os.path.join(JSON_OUT, name), "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

if __name__ == "__main__":
    print("waters:", gen_water())
    print("beans:", gen_beans())
    print("processes:", gen_processes())
    print("drippers:", gen_drippers())
    print("filters:", gen_filters())
    print("grinders:", gen_grinders())
    print("done ->", OUT)
